// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4.StudentsManagement_MVC_CodeFirst.DataAccess;

namespace _4.StudentsManagement_MVC_CodeFirst.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240501102328_NewMigration")]
    partial class NewMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_4.StudentsManagement_MVC_CodeFirst.DataAccess.Entities.ClassRoom", b =>
                {
                    b.Property<string>("ClassId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassDescriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassId");

                    b.ToTable("ClassRoom");
                });

            modelBuilder.Entity("_4.StudentsManagement_MVC_CodeFirst.DataAccess.Entities.ClassRoomLectures", b =>
                {
                    b.Property<string>("ClassId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LectureId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ClassId", "LectureId");

                    b.HasIndex("LectureId");

                    b.ToTable("ClassRoomLectures");
                });

            modelBuilder.Entity("_4.StudentsManagement_MVC_CodeFirst.DataAccess.Entities.ClassRoomStudents", b =>
                {
                    b.Property<string>("ClassId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ClassId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ClassRoomStudents");
                });

            modelBuilder.Entity("_4.StudentsManagement_MVC_CodeFirst.DataAccess.Entities.Lecture", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnBoard")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("_4.StudentsManagement_MVC_CodeFirst.DataAccess.Entities.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<float>("GPA")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("_4.StudentsManagement_MVC_CodeFirst.DataAccess.Entities.ClassRoomLectures", b =>
                {
                    b.HasOne("_4.StudentsManagement_MVC_CodeFirst.DataAccess.Entities.ClassRoom", "ClassRoom")
                        .WithMany("ClassRoomLectures")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_4.StudentsManagement_MVC_CodeFirst.DataAccess.Entities.Lecture", "Lecture")
                        .WithMany("ClassRoomLectures")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassRoom");

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("_4.StudentsManagement_MVC_CodeFirst.DataAccess.Entities.ClassRoomStudents", b =>
                {
                    b.HasOne("_4.StudentsManagement_MVC_CodeFirst.DataAccess.Entities.ClassRoom", "ClassRoom")
                        .WithMany("ClassRoomStudents")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_4.StudentsManagement_MVC_CodeFirst.DataAccess.Entities.Student", "Student")
                        .WithMany("ClassRoomStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassRoom");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("_4.StudentsManagement_MVC_CodeFirst.DataAccess.Entities.ClassRoom", b =>
                {
                    b.Navigation("ClassRoomLectures");

                    b.Navigation("ClassRoomStudents");
                });

            modelBuilder.Entity("_4.StudentsManagement_MVC_CodeFirst.DataAccess.Entities.Lecture", b =>
                {
                    b.Navigation("ClassRoomLectures");
                });

            modelBuilder.Entity("_4.StudentsManagement_MVC_CodeFirst.DataAccess.Entities.Student", b =>
                {
                    b.Navigation("ClassRoomStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
